Kartverket.MetadataMonitor/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kartverket.MetadataMonitor.Models;
using log4net;

namespace Kartverket.MetadataMonitor.Controllers
{
    [HandleError]
    public class ReportController : Controller
    {
        private readonly MetadataRepository _metadataRepository;

        private static readonly ILog Log = LogManager.GetLogger(typeof(MvcApplication));

        public ReportController() :this(new MetadataRepository()) { }

        private ReportController(MetadataRepository metadataRepository)
        {
            _metadataRepository = metadataRepository;
        }


        public ActionResult Index(string organization, string resource, bool? inspire, List<int> fields)
        {

            ViewBag.Organizations = new SelectList(_metadataRepository.GetAvailableOrganizations(), organization);

            List<string> resourceTypes = new List<string>()
                {
                    "service", "dataset", "series", "software", "unknown"
                };
            ViewBag.ResourceTypes = new SelectList(resourceTypes, resource);

            IDictionary<bool, string> inspireOptions = new Dictionary<bool, string>
                {
                    {true, "Inspire"},
                    {false, "Norge Digitalt"}
                };
            ViewBag.InspireOptions = new SelectList(inspireOptions, "Key", "Value", inspire);

            IDictionary<int, string> availableFields = new Dictionary<int, string>
                {
                    {1, "Kontaktinformasjon"},
                    {2, "Sammendrag"},
                    {3, "Formål"},
                    {4, "Nøkkelord"}
                };
            ViewBag.AvailableFields = new MultiSelectList(availableFields, "Key", "Value", fields);

            List<MetadataEntry> metadataEntries = _metadataRepository.GetMetadataList(organization, resource, inspire);

            var model = new ReportViewModel()
            {
                Organization = organization,
                ResourceType = resource,
                Inspire = inspire,
                MetadataEntries = metadataEntries,
                Fields = fields
            };

            return View(model);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            Log.Error("Error", filterContext.Exception);
        }

    }
}

Kartverket.MetadataMonitor/Controllers/ValidatorController.cs
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using Kartverket.MetadataMonitor.Models;

namespace Kartverket.MetadataMonitor.Controllers
{
    [HandleError]
    public class ValidatorController : Controller
    {
        private static readonly log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private readonly MetadataRepository _metadataRepository;
        private readonly ValidatorService _validatorService;

        private ValidatorController(MetadataRepository metadataRepository, ValidatorService validatorService)
        {
            _metadataRepository = metadataRepository;
            _validatorService = validatorService;
        }

        public ValidatorController() : this(new MetadataRepository(), new ValidatorService()) { }

        public ActionResult Index(int? status, string organization, string resource, bool? inspire)
        {
            List<MetadataEntry> metadataEntries = _metadataRepository.GetMetadataListWithLatestValidationResult(status, organization, resource, inspire, null);

            var myTimeZone = TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time");

            ViewBag.KartkatalogUrl = System.Web.Configuration.WebConfigurationManager.AppSettings["KartkatalogUrl"];

            var model = new ValidatorResultViewModel()
                {
                    Organization = organization,
                    Status = status,
                    ResourceType = resource,
                    Inspire = inspire,
                    MetadataEntries = metadataEntries
                };

            ViewBag.Organizations = new SelectList(_metadataRepository.GetAvailableOrganizations(), organization);
            IDictionary<int, string> statusOptions = new Dictionary<int, string>
                {
                    {1, "OK"},
                    {0, "Feil"},
                    {-1, "Ikke validert"}
                };
            ViewBag.StatusOptions = new SelectList(statusOptions, "Key", "Value", status);

            List<string> resourceTypes = new List<string>()
                {
                    "service", "dataset", "series", "software", "unknown"
                };
            ViewBag.ResourceTypes = new SelectList(resourceTypes, resource);

            IDictionary<bool, string> inspireOptions = new Dictionary<bool, string>
                {
                    {true, "Inspire"},
                    {false, "Norge Digitalt"}
                };
            ViewBag.InspireOptions = new SelectList(inspireOptions, "Key", "Value", inspire);

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult RunValidate(string uuid, string organization, string resource, int? status, bool? inspire)
        {
            if (string.IsNullOrEmpty(uuid))
                uuid = "9d118d31-182c-495b-b7be-d819cc7444b1";

            
            MetadataEntry metadataEntry = _validatorService.ValidateMetadata(uuid);

            string message = "Validering gjennomført!";

            if (metadataEntry == null) {
                message = "Validering feilet pga en ukjent feil.";
            }
            else if (metadataEntry.isNotValidated())
            {
                message = "Validering feilet: " + metadataEntry.GetValidationResultMesssages();
            }
            
            TempData["message"] = message;

            return RedirectToAction("Index", new
                {
                    organization = organization, 
                    status = status, 
                    resource = resource,
                    inspire = inspire
                });
        }

        [HttpGet]
        public ActionResult ValidateAll()
        {
            Log.Info("Start validating all metadata.");            

            new Thread(() => new ValidatorService().ValidateAllMetadata(false)).Start();

            TempData["message"] = "Full validering startet!";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeactivateValidateAll()
        {
            Log.Info("Start validating all metadata, with deactivating.");

            new Thread(() => new ValidatorService().ValidateAllMetadata(true)).Start();

            TempData["message"] = "Full validering startet! - med deaktivering";

            return RedirectToAction("Index");
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            Log.Error("Error", filterContext.Exception);
        }

    }
}

Kartverket.MetadataMonitor/Views/Validator/Index.cshtml
@using Kartverket.MetadataMonitor.Resources
@using Kartverket.MetadataMonitor.Models
@model Kartverket.MetadataMonitor.Models.ValidatorResultViewModel
@{
    ViewBag.Title = UI.ValidationResults;
    ViewBag.Description = UI.ValidationResultsDescription;
}

@section breadcrumb{
    <li>@UI.ValidationResults</li>
}

@if (TempData["message"] != null)
{
    <div class="row">
        <div class="alert alert-info span6">
            <p>@TempData["message"]</p>
        </div>
    </div>
}

@section PageHeader
{
    <form method="GET" action="@Url.Action("Index")">
        <div class="form-group">
            <div class="row">
                <div class="col-md-3">
                    <label class="control-label" for="organization">
                        Organisasjon
                    </label>
                    <div class="custom-select">
                        @Html.DropDownList("organization", (SelectList)ViewBag.Organizations, "", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-2">
                    <label class="control-label" for="status">
                        Status
                    </label>
                    <div class="custom-select">
                        @Html.DropDownList("status", (SelectList)ViewBag.StatusOptions, "", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-2">
                    <label class="control-label" for="resource">
                        Ressurstype
                    </label>
                    <div class="custom-select">
                        @Html.DropDownList("resource", (SelectList)ViewBag.ResourceTypes, "", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-3">
                    <label class="control-label" for="inspire">
                        Tilhørighet
                    </label>
                    <div class="custom-select">
                        @Html.DropDownList("inspire", (SelectList)ViewBag.InspireOptions, "", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-2">
                    <input type="submit" value="Filtrer resultater" class="btn no-label" />
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col-md-2">
            <a href="@Url.Action("Index", "Report", new { organization = Model.Organization, resource = Model.ResourceType, inspire = Model.Inspire})" class="btn" role="button">Gå til rapportvisning</a>
        </div>
    </div>

    <p class="">@Model.MetadataEntries.Count resultater</p>
}

@if (Model.MetadataEntries.Any())
{
    <table class="table table-striped sortable" style="table-layout: fixed">
        <thead>
            <tr>
                <th>Tittel</th>
                <th>Organisasjon</th>
                <th width="5%">XML</th>
                <th>Ressurstype</th>
                <th>Type</th>
                <th width="15%">Status</th>
                <th>Interoperabilitet</th>
                <th width="20%">Feilmeldinger</th>
                <th width="5%">Rapport</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var result in Model.MetadataEntries)
            {
                var linkText = result.Title;
                if (linkText == null) { linkText = result.Uuid; }

                var statusClass = "label-warning";
                var statusText = "Ikke validert";

                if (result.IsOk())
                {
                    statusClass = "label-success";
                    statusText = "OK";
                }
                else if (result.IsFailed())
                {
                    statusClass = "label-danger";
                    statusText = "FEIL";
                }

                if (result.ValidationResults[0].CompletenessIndicator != ValidationResult.UndefinedIndicator)
                {
                    statusText += String.Format("   {0} %", Math.Round(result.ValidationResults[0].CompletenessIndicator));
                }

                string interoperability = "";

                if (result.ValidationResults[0].InteroperabilityIndicator != ValidationResult.UndefinedIndicator)
                {
                    interoperability = String.Format("{0} %", Math.Round(result.ValidationResults[0].InteroperabilityIndicator));
                }

            <tr>
                <td style="word-break: break-all;">
                    <p>
                        <a href="@(ViewBag.KartkatalogUrl)metadata/uuid/@result.Uuid" target="_blank">@linkText</a><br />
                        <div class="text-small">@result.Uuid</div>

                    </p>
                </td>
                <td style="word-break: break-all;">
                    <p>@result.ResponsibleOrganization</p>
                </td>
                <td class="content-align-center">
                    <a href="http://www.geonorge.no/geonetwork/srv/eng/xml_iso19139?uuid=@result.Uuid" target="_blank">
                        <i class="glyphicon glyphicon-file"></i>
                    </a>
                </td>
                <td style="word-break: break-all;">
                    <div>@result.ResourceType</div>
                </td>
                <td>
                    @if (result.InspireResource)
                    {
                        <text>INSPIRE</text>
                    }
                    else
                    {
                        <text>Norge Digitalt</text>
                    }
                </td>
                <td style="word-break: break-all;">
                    <span class="label @statusClass">@statusText</span>
                    <p class="text-small">@result.ValidationResults[0].Timestamp.ToString("dd'.'MM'.'yyyy HH':'mm':'ss")</p>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <p>
                            <a href="@Url.Action("RunValidate", new
                                               {
                                                   uuid = @result.Uuid,
                                                   status=@Model.Status,
                                                   organization=@Model.Organization,
                                                   resource=@Model.ResourceType,
                                                   inspire = @Model.Inspire
                                               })" class="btn" role="button">
                                <i class="glyphicon glyphicon-play"></i> Validering
                            </a>
                        </p>
                    }
                </td>
                <td style="word-break: break-all;">
                    <div>@interoperability</div>
                </td>
                <td style="word-break: break-all;">
                    @if (result.ValidationResults[0].Messages != null)
                    {
                        <ul>
                            @foreach (var error in result.ValidationResults[0].Messages.Split('\n'))
                            {
                                if (!string.IsNullOrEmpty(error))
                                {
                                    <li>@error</li>
                                }
                            }
                        </ul>
                    }
                </td>
                <td class="content-align-center">
                    @if (!String.IsNullOrWhiteSpace(result.ValidationResults[0].ReportUrl))
                    {
                        <a href="@result.ValidationResults[0].ReportUrl" target="_blank">
                            <i class="glyphicon glyphicon-file"></i>
                        </a>
                    }
                </td>
            </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Ingen resultater.</p>
}

@section scripts
{
    <script src="~/Scripts/sorttable.js"></script>
    <script src="~/Scripts/jquery.placeholder.js"></script>
}

@section login
{
    <p></p>
    <div class="row">
        <div class="col-md-12">
            @if (User.Identity.IsAuthenticated)
    {
                <form method="POST" action="@Url.Action("Logout", "Account")" class="navbar-form pull-right">
                    <input type="submit" class="btn no-label" value="Logg ut" />
                </form>
            }
            else
            {
                <form method="POST" action="@Url.Action("Login", "Account")">
                    <div class="row">
                        <div class="col-md-3">
                            <label class="control-label" for="username">
                                Brukernavn
                            </label>
                            <input type="text" class="form-control" name="username" placeholder="Brukernavn" />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label" for="password">
                                Passord
                            </label>
                            <input type="password" class="form-control" name="password" placeholder="Passord" />
                        </div>
                        <div class="col-md-2">
                            <input type="submit" class="btn no-label" value="Logg inn" />
                        </div>
                    </div>
                </form>
            }
            <div class="clearfix"></div>
            <hr />
        </div>
    </div>
}