Kartverket.MetadataMonitor/Models/ReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kartverket.MetadataMonitor.Models
{
    public class ReportViewModel
    {
        public string Organization { get; set; }
        public string ResourceType { get; set; }
        public bool? Inspire { get; set; }

        public List<MetadataEntry> MetadataEntries { get; set; }

        public List<int> Fields { get; set; } 
    }
}

Kartverket.MetadataMonitor/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kartverket.MetadataMonitor.Models;
using log4net;

namespace Kartverket.MetadataMonitor.Controllers
{
    [HandleError]
    public class ReportController : Controller
    {
        private readonly MetadataRepository _metadataRepository;

        private static readonly ILog Log = LogManager.GetLogger(typeof(MvcApplication));

        public ReportController() :this(new MetadataRepository()) { }

        private ReportController(MetadataRepository metadataRepository)
        {
            _metadataRepository = metadataRepository;
        }


        public ActionResult Index(string organization, string resource, bool? inspire, List<int> fields)
        {

            ViewBag.Organizations = new SelectList(_metadataRepository.GetAvailableOrganizations(), organization);

            List<string> resourceTypes = new List<string>()
                {
                    "service", "dataset", "series", "software", "unknown"
                };
            ViewBag.ResourceTypes = new SelectList(resourceTypes, resource);

            IDictionary<bool, string> inspireOptions = new Dictionary<bool, string>
                {
                    {true, "Inspire"},
                    {false, "Norge Digitalt"}
                };
            ViewBag.InspireOptions = new SelectList(inspireOptions, "Key", "Value", inspire);

            IDictionary<int, string> availableFields = new Dictionary<int, string>
                {
                    {1, "Kontaktinformasjon"},
                    {2, "Sammendrag"},
                    {3, "Formål"},
                    {4, "Nøkkelord"}
                };
            ViewBag.AvailableFields = new MultiSelectList(availableFields, "Key", "Value", fields);

            List<MetadataEntry> metadataEntries = _metadataRepository.GetMetadataList(organization, resource, inspire);

            var model = new ReportViewModel()
            {
                Organization = organization,
                ResourceType = resource,
                Inspire = inspire,
                MetadataEntries = metadataEntries,
                Fields = fields
            };

            return View(model);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            Log.Error("Error", filterContext.Exception);
        }

    }
}

Kartverket.MetadataMonitor/Controllers/ValidatorController.cs
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using Kartverket.MetadataMonitor.Models;

namespace Kartverket.MetadataMonitor.Controllers
{
    [HandleError]
    public class ValidatorController : Controller
    {
        private static readonly log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private readonly MetadataRepository _metadataRepository;
        private readonly ValidatorService _validatorService;

        private ValidatorController(MetadataRepository metadataRepository, ValidatorService validatorService)
        {
            _metadataRepository = metadataRepository;
            _validatorService = validatorService;
        }

        public ValidatorController() : this(new MetadataRepository(), new ValidatorService()) { }

        public ActionResult Index(int? status, string organization, string resource, bool? inspire)
        {
            List<MetadataEntry> metadataEntries = _metadataRepository.GetMetadataListWithLatestValidationResult(status, organization, resource, inspire, null);

            var myTimeZone = TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time");

            ViewBag.KartkatalogUrl = System.Web.Configuration.WebConfigurationManager.AppSettings["KartkatalogUrl"];

            var model = new ValidatorResultViewModel()
                {
                    Organization = organization,
                    Status = status,
                    ResourceType = resource,
                    Inspire = inspire,
                    MetadataEntries = metadataEntries
                };

            ViewBag.Organizations = new SelectList(_metadataRepository.GetAvailableOrganizations(), organization);
            IDictionary<int, string> statusOptions = new Dictionary<int, string>
                {
                    {1, "OK"},
                    {0, "Feil"},
                    {-1, "Ikke validert"}
                };
            ViewBag.StatusOptions = new SelectList(statusOptions, "Key", "Value", status);

            List<string> resourceTypes = new List<string>()
                {
                    "service", "dataset", "series", "software", "unknown"
                };
            ViewBag.ResourceTypes = new SelectList(resourceTypes, resource);

            IDictionary<bool, string> inspireOptions = new Dictionary<bool, string>
                {
                    {true, "Inspire"},
                    {false, "Norge Digitalt"}
                };
            ViewBag.InspireOptions = new SelectList(inspireOptions, "Key", "Value", inspire);

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult RunValidate(string uuid, string organization, string resource, int? status, bool? inspire)
        {
            if (string.IsNullOrEmpty(uuid))
                uuid = "9d118d31-182c-495b-b7be-d819cc7444b1";

            
            MetadataEntry metadataEntry = _validatorService.ValidateMetadata(uuid);

            string message = "Validering gjennomført!";

            if (metadataEntry == null) {
                message = "Validering feilet pga en ukjent feil.";
            }
            else if (metadataEntry.isNotValidated())
            {
                message = "Validering feilet: " + metadataEntry.GetValidationResultMesssages();
            }
            
            TempData["message"] = message;

            return RedirectToAction("Index", new
                {
                    organization = organization, 
                    status = status, 
                    resource = resource,
                    inspire = inspire
                });
        }

        [HttpGet]
        public ActionResult ValidateAll()
        {
            Log.Info("Start validating all metadata.");            

            new Thread(() => new ValidatorService().ValidateAllMetadata(false)).Start();

            TempData["message"] = "Full validering startet!";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeactivateValidateAll()
        {
            Log.Info("Start validating all metadata, with deactivating.");

            new Thread(() => new ValidatorService().ValidateAllMetadata(true)).Start();

            TempData["message"] = "Full validering startet! - med deaktivering";

            return RedirectToAction("Index");
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            Log.Error("Error", filterContext.Exception);
        }

    }
}

Kartverket.MetadataMonitor/Views/Report/Index.cshtml
@using Kartverket.MetadataMonitor.Resources
@model Kartverket.MetadataMonitor.Models.ReportViewModel
@{
    ViewBag.Title = @UI.ReportView;
}

@section breadcrumb{
    <li>@UI.ReportView</li>
}

@section PageHeader
{
    <form method="GET" action="@Url.Action("Index")">
        <div class="form-group">
            <div class="row">
                <div class="col-md-3">
                    <label class="control-label" for="organization">
                        Organisasjon
                    </label>
                    <div class="custom-select">
                        @Html.DropDownList("organization", (SelectList)ViewBag.Organizations, "", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-2">
                    <label class="control-label" for="resource">
                        Ressurstype:
                    </label>
                    <div class="custom-select">
                        @Html.DropDownList("resource", (SelectList)ViewBag.ResourceTypes, "", new { @class = "form-control"})
                    </div>
                </div>
                <div class="col-md-2">
                    <label class="control-label" for="inspire">
                        Tilhørighet:
                    </label>
                    <div class="custom-select">
                        @Html.DropDownList("inspire", (SelectList)ViewBag.InspireOptions, "", new { @class = "form-control"})
                    </div>
                </div>
                <div class="col-md-3">
                    <label class="control-label" for="fields">Velg felter som skal vises:</label>
                    @Html.ListBox("fields", ViewBag.AvailableFields as MultiSelectList, new { multiple = "multiple", @class = "chosen-select", data_placeholder = "- Velg felter -" })
                </div>
                <div class="col-md-2">
                    <input type="submit" value="Vis rapport" class="btn no-label" />
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col-md-2">
            <a href="@Url.Action("Index","Validator", new { organization = Model.Organization, resource = Model.ResourceType, inspire = Model.Inspire})" class="btn btn-primary btn-sm" role="button">Vis valideringsresultater</a>

        </div>
    </div>


    <p class="">@Model.MetadataEntries.Count resultater</p>
}

@if (Model.MetadataEntries.Any())
{
    <table class="table table-striped sortable" style="table-layout: fixed">
        <thead>
            <tr>
                <th style="width: 20%">Tittel</th>
                <th style="width: 20%">Organisasjon</th>
                @if (Model.Fields != null)
                {
                    if (Model.Fields.Contains(1))
                    {
                        <th>Kontaktinformasjon</th>
                    }
                    if (Model.Fields.Contains(2))
                    {
                        <th>Sammendrag</th>
                    }
                    if (Model.Fields.Contains(3))
                    {
                        <th>Formål</th>
                    }
                    if (Model.Fields.Contains(4))
                    {
                        <th>Nøkkelord</th>
                    }
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var result in Model.MetadataEntries)
            {
                var linkText = result.Title;
                if (linkText == null) { linkText = result.Uuid; }

                <tr>
                    <td>
                        <p>
                            <a href="http://www.geonorge.no/geonetwork/?uuid=@result.Uuid" target="_blank">@linkText</a>
                        </p>
                    </td>
                    <td>
                        <p>@result.ResponsibleOrganization</p>
                    </td>
                    @if (Model.Fields != null)
                    {
                        if (Model.Fields.Contains(1))
                        {
                            <td>
                                <span style="white-space: pre-line">@result.ContactInformation</span>
                            </td>
                        }
                        if (Model.Fields.Contains(2))
                        {
                            <td>@result.Abstract</td>
                        }
                        if (Model.Fields.Contains(3))
                        {
                            <td>@result.Purpose</td>
                        }
                        if (Model.Fields.Contains(4))
                        {
                            <td>@result.Keywords</td>
                        }
                    }

                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Ingen resultater.</p>
}

@section scripts
{
    <script src="~/Scripts/sorttable.js"></script>
    <script src="~/Scripts/jquery.placeholder.js"></script>
  
    <script>
        $(function () {
            /* activate chosen, http://harvesthq.github.com/chosen/ */
            $(".chosen-select").chosen();
        });
    </script>
}

@section login
{
    <p></p>
    <div class="row">
        <div class="col-md-12">
            @if (User.Identity.IsAuthenticated)
    {
                <form method="POST" action="@Url.Action("Logout", "Account")" class="navbar-form pull-right">
                    <input type="submit" class="btn no-label" value="Logg ut" />
                </form>
            }
            else
            {
                <form method="POST" action="@Url.Action("Login", "Account")">
                    <div class="row">
                        <div class="col-md-3">
                            <label class="control-label" for="username">
                                Brukernavn
                            </label>
                            <input type="text" class="form-control" name="username" placeholder="Brukernavn" />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label" for="password">
                                Passord
                            </label>
                            <input type="password" class="form-control" name="password" placeholder="Passord" />
                        </div>
                        <div class="col-md-2">
                            <input type="submit" class="btn no-label" value="Logg inn" />
                        </div>
                    </div>
                </form>
            }
            <div class="clearfix"></div>
            <hr />
        </div>
    </div>
}